### ISSUE TITLE
Schematic parse failure

### ISSUE THREAD

**Issue by avishorp** [xesscorp/KiField#26]
[This schematic](https://raw.githubusercontent.com/avishorp/hitem/master/board/hitem.sch) fails to parse, with this error:

> Traceback (most recent call last):
  File "/home/local/temp/kifield/bin/kifield", line 11, in <module>
    sys.exit(main())
  File "/home/local/temp/kifield/lib/python2.7/site-packages/kifield/__main__.py", line 161, in main
    recurse=args.recurse)
  File "/home/local/temp/kifield/lib/python2.7/site-packages/kifield/kifield.py", line 1119, in kifield
    part_fields_dict = extract_part_fields(extract_filenames, inc_field_names, exc_field_names, recurse)
  File "/home/local/temp/kifield/lib/python2.7/site-packages/kifield/kifield.py", line 678, in extract_part_fields
    f_part_fields_dict = extraction_functions[f_extension](f, inc_field_names, exc_field_names, recurse)
  File "/home/local/temp/kifield/lib/python2.7/site-packages/kifield/kifield.py", line 457, in extract_part_fields_from_sch
    sch = Schematic(filename)  # Read in the schematic.
  File "/home/local/temp/kifield/lib/python2.7/site-packages/kifield/sch.py", line 193, in __init__
    self.components.append(Component(block_data))
  File "/home/local/temp/kifield/lib/python2.7/site-packages/kifield/sch.py", line 47, in __init__
    line = list(s)
  File "/usr/lib64/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib64/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib64/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

I added a line counter to try to locate the error, and it seem to fail at line 800. I haven't spotted any problem with that line.

**Comment by xesscorp** [comment]
Sorry for the delay. I tested the file and didn't see a problem. Re-open this if it still affects you.
