### ISSUE TITLE
Fails, apparently during CSV-> XLSX conversion

### ISSUE THREAD

**Issue by p2pb** [xesscorp/KiField#54]
Running latest release (0.1.14), latest Python on Windows.  We don't need XLSX, a way of turning off the attempted conversion to XLSX would probably be a sufficient fix..

```
C:\Users\Paul\Documents\p5t4ps>kifield -x p5t4ps.sch -i variant-0.csv -d 1
Extracting fields +[], -[] from files ['p5t4ps.sch'].
Extracting fields [], -[] from schematic file p5t4ps.sch.
Inserting extracted fields into files ['variant-0.csv'].
Inserting extracted fields into CSV file variant-0.csv.
Traceback (most recent call last):
  File "c:\users\paul\appdata\local\programs\python\python37-32\lib\site-packages\kifield\kifield.py", line 765, in insert_part_fields_into_wb
    for h in headers}
  File "c:\users\paul\appdata\local\programs\python\python37-32\lib\site-packages\kifield\kifield.py", line 765, in <dictcomp>
    for h in headers}
  File "c:\users\paul\appdata\local\programs\python\python37-32\lib\site-packages\openpyxl\utils\cell.py", line 123, in column_index_from_string
    return _COL_STRING_CACHE[str_col.upper()]
AttributeError: 'int' object has no attribute 'upper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python37-32\Scripts\kifield-script.py", line 11, in <module>
    load_entry_point('kifield==0.1.14', 'console_scripts', 'kifield')()
  File "c:\users\paul\appdata\local\programs\python\python37-32\lib\site-packages\kifield\__main__.py", line 148, in main
    backup = not args.nobackup)
  File "c:\users\paul\appdata\local\programs\python\python37-32\lib\site-packages\kifield\kifield.py", line 1219, in kifield
    insert_part_fields(part_fields_dict, insert_filenames, recurse, group_components, backup)
  File "c:\users\paul\appdata\local\programs\python\python37-32\lib\site-packages\kifield\kifield.py", line 1203, in insert_part_fields
    insertion_functions[f_extension](part_fields_dict, f, recurse, group_components, backup)
  File "c:\users\paul\appdata\local\programs\python\python37-32\lib\site-packages\kifield\kifield.py", line 880, in insert_part_fields_into_csv
    wb = insert_part_fields_into_wb(part_fields_dict, wb)
  File "c:\users\paul\appdata\local\programs\python\python37-32\lib\site-packages\kifield\kifield.py", line 768, in insert_part_fields_into_wb
    for h in headers}
  File "c:\users\paul\appdata\local\programs\python\python37-32\lib\site-packages\kifield\kifield.py", line 768, in <dictcomp>
    for h in headers}
AttributeError: module 'openpyxl.cell' has no attribute 'column_index_from_string'

C:\Users\Paul\Documents\p5t4ps>
```

**Comment by xesscorp** [comment]
Try the latest KiField 0.1.15 to see if it fixes this issue. Make sure to upgrade to the latest 2.6.0 version of openpyxl.
