### ISSUE TITLE
`python setup.py test` fails

### ISSUE THREAD

**Issue by kasbah** [xesscorp/KiField#6]
With a python3 virtualenv:

```
writing manifest file 'kifield.egg-info/SOURCES.txt'
running build_ext
error: [Errno 2] No such file or directory: 'test'
```

With a python2 virtualenv

```
writing manifest file 'kifield.egg-info/SOURCES.txt'
running build_ext
error: [Errno 2] No such file or directory: 'test'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/kaspar/projects/kitnic/KiField/venv/local/lib/python2.7/site-packages/openpyxl-2.4.0_b1-py2.7.egg/openpyxl/writer/write_only.py", line 34, in _openpyxl_shutdown
    for path in ALL_TEMP_FILES:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/kaspar/projects/kitnic/KiField/venv/local/lib/python2.7/site-packages/openpyxl-2.4.0_b1-py2.7.egg/openpyxl/writer/write_only.py", line 34, in _openpyxl_shutdown
    for path in ALL_TEMP_FILES:
TypeError: 'NoneType' object is not iterable
```

**Comment by kasbah** [comment]
Tox output:
```
$ tox
GLOB sdist-make: /home/kaspar/projects/kitnic/KiField/setup.py
py26 create: /home/kaspar/projects/kitnic/KiField/.tox/py26
ERROR: InterpreterNotFound: python2.6
py27 inst-nodeps: /home/kaspar/projects/kitnic/KiField/.tox/dist/kifield-0.1.3.zip
py27 installed: et-xmlfile==1.0.1,future==0.15.2,jdcal==1.2,kifield==0.1.3,openpyxl==2.3.5
py27 runtests: PYTHONHASHSEED='3355773274'
py27 runtests: commands[0] | python setup.py test
running test
running egg_info
writing kifield.egg-info/PKG-INFO
writing top-level names to kifield.egg-info/top_level.txt
writing entry points to kifield.egg-info/entry_points.txt
writing requirements to kifield.egg-info/requires.txt
writing dependency_links to kifield.egg-info/dependency_links.txt
reading manifest file 'kifield.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
writing manifest file 'kifield.egg-info/SOURCES.txt'
running build_ext
error: [Errno 2] No such file or directory: 'test'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/kaspar/projects/kitnic/KiField/.tox/py27/local/lib/python2.7/site-packages/openpyxl/writer/write_only.py", line 38, in _openpyxl_shutdown
    for path in ALL_TEMP_FILES:
TypeError: 'NoneType' object is not iterable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/kaspar/projects/kitnic/KiField/.tox/py27/local/lib/python2.7/site-packages/openpyxl/writer/write_only.py", line 38, in _openpyxl_shutdown
    for path in ALL_TEMP_FILES:
TypeError: 'NoneType' object is not iterable
ERROR: InvocationError: '/home/kaspar/projects/kitnic/KiField/.tox/py27/bin/python setup.py test'
py33 create: /home/kaspar/projects/kitnic/KiField/.tox/py33
ERROR: InterpreterNotFound: python3.3
py34 inst-nodeps: /home/kaspar/projects/kitnic/KiField/.tox/dist/kifield-0.1.3.zip
py34 installed: kifield==0.1.3
py34 runtests: PYTHONHASHSEED='3355773274'
py34 runtests: commands[0] | python setup.py test
running test
running egg_info
writing requirements to kifield.egg-info/requires.txt
writing dependency_links to kifield.egg-info/dependency_links.txt
writing kifield.egg-info/PKG-INFO
writing entry points to kifield.egg-info/entry_points.txt
writing top-level names to kifield.egg-info/top_level.txt
reading manifest file 'kifield.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
writing manifest file 'kifield.egg-info/SOURCES.txt'
running build_ext
error: [Errno 2] No such file or directory: 'test'
ERROR: InvocationError: '/home/kaspar/projects/kitnic/KiField/.tox/py34/bin/python setup.py test'
_____________________________________ summary ______________________________________
ERROR:   py26: InterpreterNotFound: python2.6
ERROR:   py27: commands failed
ERROR:   py33: InterpreterNotFound: python3.3
ERROR:   py34: commands failed
```

**Comment by kasbah** [comment]
@devbisme could you clarify what's in the test suite that's actually useful? I notice I can run `test_kifield.py` but it's an empty test. I am not sure what the other `tests/*.py` are intended for. They seem to expect csv file arguments but none are provided. 

Would be good to extract the useful bits out of what is there and add some unit tests.
