### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4454: character maps to <undefined>

### ISSUE THREAD

**Issue by thoonky** [xesscorp/KiField#66]
See below for error.  I am using Kicad 5.1.10

Traceback (most recent call last):
  File "c:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python39\Scripts\kifield.exe\__main__.py", line 7, in <module>
  File "c:\python\python39\lib\site-packages\kifield\__main__.py", line 141, in main
    kifield(
  File "c:\python\python39\lib\site-packages\kifield\kifield.py", line 1498, in kifield
    part_fields_dict = extract_part_fields(
  File "c:\python\python39\lib\site-packages\kifield\kifield.py", line 684, in extract_part_fields
    f_part_fields_dict = extraction_function(
  File "c:\python\python39\lib\site-packages\kifield\kifield.py", line 316, in extract_part_fields_from_sch
    sch = Schematic(filename)  # Read in the schematic.
  File "c:\python\python39\lib\site-packages\kifield\sch.py", line 233, in __init__
    self.header = f.readline()
  File "c:\python\python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4454: character maps to <undefined>

**Comment by xesscorp** [comment]
You don't mention what version of KiField you are using or how you are calling it, and you didn't attach the schematic file that caused this error. I assume the schematic probably includes some non-ASCII electrical symbol. I tried creating such a schematic and I didn't have any problem using KiField with it.

You might try the latest development version of KiField and see if that fixes your problem:
```bash
pip install git+https://github.com/xesscorp/KiField@development
```
